NDefines.NEconomy.PRIVATEER_INCOME_COLLECTION_EFF = 0
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 0

NDefines.NDiplomacy.DESIRED_NUM_OF_ELECTORS = 5
NDefines.NDiplomacy.EMPEROR_REVOKE_AUTHORITY_COST = 15.0
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = -0.0
NDefines.NDiplomacy.LACK_OF_ELECTORS_HIT = -0.1
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.25