NDefines.NCountry.CORRUPTION_FROM_BANNERS = 2
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = -0.05
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0.25
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 3.75
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.1
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 0
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 10
NDefines.NMilitary.STACKWIPE_MANPOWER_RETURN_FRACTION = 0.25
NDefines.NMilitary.WAR_LENGTH_DAMAGE_MODIFIER = 0.011
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 9.0
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0




NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 105
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
NDefines.NDiplomacy.MAX_CLIENT_STATES = 20


NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 40
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = 0
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_ASSAULT = 10
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 25
NDefines.NCountry.NOMAD_DEVELOPMENT_SCALE = 1000
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = 0
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 45
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0
NDefines.NCountry.BASE_FREE_POLICIES = 2
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 1
NDefines.NCountry.HRE_MAX_RANK = 3
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_COOLDOWN_DURATION = 450
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.PILLAGE_CAPITAL_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.PS_SCORCH_EARTH = 4
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 30
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 1
NDefines.NCountry.YEARS_OF_NATIONALISM = 10
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0.1
NDefines.NCountry.LIBERTY_DESIRE_WAR_EXHAUSTION = 0.1
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 5
NDefines.NCountry.REPUBLICAN_TRADITION_YEARLY_INCREASE = 0.8


NDefines.NEconomy.CARAVAN_FACTOR = 3
NDefines.NEconomy.CARAVAN_POWER_MAX = 10
NDefines.NEconomy.CARAVAN_POWER_MIN = 1
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 25
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 6
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 5475
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 10
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = -0.2


NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES= 60
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.1
NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 10
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.MERCENARY_COMPANY_BUILDING_TIME = 0.4
NDefines.NMilitary.MERCENARY_COMPANY_ARMY_TRADITION = 15.0
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1
NDefines.NMilitary.ARMY_ATTRITION_AT_COAST = 1
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 4
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 15.0
NDefines.NMilitary.SLACKEN_AP_DROP = 0.25
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.1
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.1
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2
NDefines.NMilitary.ASSAULT_ATTACKER_LOSS = 2.0
NDefines.NMilitary.COSSACKS_SHOCK_DAMAGE_BONUS = 0.15

NDefines.NMilitary.RESERVE_TICK_DAMAGE = 0.06
NDefines.NMilitary.FLAGSHIP_REQUIRED_NAVY_SIZE_IN_SAILORS = 1000
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 60
NDefines.NMilitary.NAVAL_DOCTRINE_SAILORS_COST = 0.05
NDefines.NMilitary.NAVAL_DOCTRINE_MIN_FORCE_LIMIT = 10

NDefines.NAI.MIN_CAV_PERCENTAGE = 0.0 --AI will always try to have at least this many % of their army as cav, regardless of time in the game
NDefines.NAI.MAX_CAV_PERCENTAGE = 100
NDefines.NAI.SUBSIDY_YEARS = -1
NDefines.NAI.AGGRESSIVENESS = 1000
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 900
NDefines.NAI.MISSION_PICK_CHANCE = 100
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 1
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 1
NDefines.NAI.ARTILLERY_FRACTION = 0.35
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 13
NDefines.NAI.INCOME_SAVINGS_FRACTION = -1
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 0.001
NDefines.NAI.MILITARISE_FORT_BUDGET_FACTOR = 0.1
NDefines.NAI.DESIRED_SURPLUS = 0.01
NDefines.NAI.DESIRED_DEFICIT = 0.01
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.05
NDefines.NAI.MAX_SAVINGS = -1
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.9
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.15
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.1
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.1
NDefines.NAI.ARMY_BUDGET_FRACTION = 1
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.1
NDefines.NAI.FORT_BUDGET_FRACTION = 0.15
NDefines.NAI.REGIMENTS_PER_GENERAL = 24
NDefines.NAI.MIN_SHIPS_FOR_ADMIRAL = 10
NDefines.NAI.MIN_SHIPS_FOR_TEST_MONARCH_MILITARY_SKILL = 25
NDefines.NAI.MIN_AI_ADMIRALS_WANTED = 1
NDefines.NAI.MAX_AI_ADMIRALS_WANTED_WARTIME = 3
NDefines.NAI.MAX_AI_ADMIRALS_WANTED_PEACETIME = 2
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 135
NDefines.NAI.FORCE_MARCH_MIN_SIZE = 5
NDefines.NAI.FORCE_MARCH_ALWAYS_SIZE = 10000
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 175
NDefines.NAI.PURSUE_DISTANCE = 50
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 1
NDefines.NAI.GOVERNING_CAPACITY_REFORM_PROGRESS_GAP_TOLERANCE = 50
NDefines.NAI.GOVERNING_CAPACITY_REFORM_BIAS_IF_NEEDED = 100
NDefines.NAI.DANGEROUS_OVEREXTENSION_PERCENTAGE = 0.1

NDefines.NAI.DEBASE_THRESHOLD = 10000

NDefines.NAI.DEVELOPMENT_CAP_BASE = 20
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1

NDefines.NAI.PEACE_BASE_RELUCTANCE = 0 -- AI base stubbornness to refuse peace (always applied)
NDefines.NAI.PEACE_BATTLE_RELUCTANCE = 60 -- Reluctance multiplied by fraction of support limit currently in an ongoing battle in this war (to encourage battle resolution before peacing)
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_FACTOR = 0.005 -- AI unwillingness to peace based on demanding more stuff than you have warscore
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_THRESHOLD = 20 -- If you have less warscore than this, excessive demands will be factored in more highly
NDefines.NAI.PEACE_TIME_MONTHS = 12 -- Months of additional AI stubbornness in a war
NDefines.NAI.PEACE_TIME_MAX_MONTHS = 600 -- Max months applied to time factor in a war
NDefines.NAI.PEACE_TIME_EARLY_FACTOR = 0.75 -- During months of stubbornness the effect of time passed is multiplied by this
NDefines.NAI.PEACE_TIME_LATE_FACTOR = 1.0 -- After months of stubbornness the effect of time passed is multiplied by this (only applied to positive war enthusiasm)
NDefines.NAI.PEACE_STALLED_WAR_TIME_FACTOR = 0.34 -- Applied to number of years war has been stalled to determine how much positive war enthusiasm is reduced
NDefines.NAI.PEACE_STALLED_WAR_THRESHOLD = 3 -- If the warscore has changed by this amount or less in the last year, the war is stalled
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 1.0 -- AI willingness to peace based on war exhaustion
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 10 -- Threshold for when PEACE_HIGH_WAR_EXHAUSTION_FACTOR is applied
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 2.0 -- Additional AI willingness to peace based on war exhaustion above the high threshold
NDefines.NAI.PEACE_WAR_DIRECTION_FACTOR = 0.5 -- AI willingness to peace based on who's making gains in the war
NDefines.NAI.PEACE_WAR_DIRECTION_WINNING_MULT = 5.0 -- Multiplies AI emphasis on war direction if it's the one making gains
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0.2 -- AI willingness to peace based on strength estimation of both sides
NDefines.NAI.PEACE_INDEPENDENCE_FACTOR = 50 -- Revolting AI's unwillingness to peace while between -5 and cost of independence wargoal in an independence war
NDefines.NAI.PEACE_WARGOAL_FACTOR = 0.5 -- AI unwillingness to peace based on holding the wargoal
NDefines.NAI.PEACE_CAPITAL_FACTOR = 5 -- AI unwillingness to peace based on holding their own capital
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 10 -- AI unwillingness to peace based on manpower & forcelimits
NDefines.NAI.PEACE_ALLY_BASE_RELUCTANCE_MULT = 2.0 -- Multiplies PEACE_BASE_RELUCTANCE for allies in a war
NDefines.NAI.PEACE_ALLY_WARSCORE_MULT = 1 -- How much extra war enthusiasm from overall warscore allies in a war get
NDefines.NAI.PEACE_ALLY_TIME_MULT = 1.0 -- Multiplies PEACE_TIME_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_EXCESSIVE_DEMANDS_MULT = 2.0 -- Multiplies PEACE_EXCESSIVE_DEMANDS_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_WAR_EXHAUSTION_MULT = 1.0 -- Multiplies PEACE_WAR_EXHAUSTION_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_WAR_DIRECTION_MULT = 0 -- Multiplies PEACE_WAR_DIRECTION_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_FORCE_BALANCE_MULT = 0 -- Multiplies PEACE_FORCE_BALANCE_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_WARGOAL_MULT = 2 -- Multiplies PEACE_WARGOAL_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_CAPITAL_MULT = 1 -- Multiplies PEACE_CAPITAL_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_MILITARY_STRENGTH_MULT = 2.0 -- Multiplies PEACE_MILITARY_STRENGTH_FACTOR for allies in a war
NDefines.NAI.PEACE_OTHER_WAR_FORCE_BALANCE_MULT = 0.5 -- Multiplies the force balance of other countries who are involved in a different war with either side
NDefines.NAI.PEACE_INCONCLUSIVE_THRESHOLD = 10	-- no demands will be accepted by AI if under this warscore
NDefines.NAI.PEACE_DESPERATION_FACTOR = 20 -- AI willingness to peace based on desperation from occupied homelands
NDefines.NAI.PEACE_ALLY_DESPERATION_MULT = 1.0 -- Multiplies PEACE_DESPERATION_FACTOR for allies in a war
NDefines.NAI.PEACE_REBELS_FACTOR = 20 -- AI willingness to peace based on number of revolts in their provinces
NDefines.NAI.PEACE_COALITION_FACTOR = 30 -- AI unwillingness to peace based on being in a coalition war
NDefines.NAI.PEACE_ALLY_REBELS_MULT = 1.0 -- Multiplies PEACE_REBELS_FACTOR for allies in a war
NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 50 -- How much AI wants to peace out when player enabled AI setting "Seek Quick Peace"
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 0	-- How much AI wants peace based on having call for peace
NDefines.NAI.PEACE_MANDATE_THREAT_FACTOR = 0.5  -- Modifies how much AI wants peace based on threat to celestial empire mandate

NDefines.NAI.PEACE_TERMS_BASE_SCORE = 10 -- Base AI scoring for any peace demand
NDefines.NAI.PEACE_RANDOM_FACTOR = 0.75 -- How much randomness is applied to AI weighting (as a fraction of the goal score)
NDefines.NAI.PEACE_TERMS_CB_MULT = 2.0 -- AI desire for a wargoal is multiplied by this for having the right CB
NDefines.NAI.PEACE_TERMS_STRATEGY_MULT = 0.5 -- AI desire for a wargoal is multiplied by this if it doesn't fit into their general strategy
NDefines.NAI.PEACE_TERMS_MIN_SCORE = 1 -- AI "does not want" peace treaties that get a lower score than this (modified by ai personality)

NDefines.NAI.PEACE_TERMS_REVOKE_ELECTOR_BASE_MULT = 1000.0 -- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_INDEPENDENCE_BASE_MULT = 1000.0 -- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_UNION_BASE_MULT = 1000.0 -- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_VASSAL_BASE_MULT = 1000.0 -- only applied if the AI has vassalize priority
NDefines.NAI.PEACE_TERMS_TAKE_MANDATE_BASE_MULT = 1000.0
NDefines.NAI.PEACE_TERMS_CHANGE_GOVERNMENT_BASE_MULT = 0.75 -- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_CHANGE_RELIGION_BASE_MULT = 100.0 -- only applied if CB is valid for it
NDefines.NAI.PEACE_TERMS_ANNEX_BASE_MULT = 100.0
NDefines.NAI.PEACE_TERMS_PILLAGE_CAPITAL_MULT = 0.5
NDefines.NAI.PEACE_TERMS_PROVINCE_BASE_MULT = 9.0
NDefines.NAI.PEACE_TERMS_TRADE_POWER_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_HUMILIATE_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_REVOKE_CORES_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_REVOKE_REFORM_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_RETURN_CORES_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_RELEASE_VASSALS_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSALS_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_GOLD_BASE_MULT = 0.005
NDefines.NAI.PEACE_TERMS_GIVE_UP_CLAIM_PERMANENT = 0.4
NDefines.NAI.PEACE_TERMS_CONCEDE_DEFEAT_BASE_MULT = 0.1
NDefines.NAI.PEACE_TERMS_DISMANTLE_REVOLUTION_BASE_MULT = 1000.0
NDefines.NAI.PEACE_TERMS_CHANGE_HRE_RELIGION_BASE_MULT = 1000.0
NDefines.NAI.PEACE_TERMS_HUMILIATE_RIVAL_BASE_MULT = 1.0
NDefines.NAI.PEACE_TERMS_ENFORCE_REBEL_DEMANDS_BASE_MULT = 1000.0
NDefines.NAI.PEACE_TERMS_TRIBUTARY_BASE_MULT = 5.0 -- Multiplies with strategic interest of making them our Tributary

NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 0.25 --AI Emperor's desire for a province is multiplied by this if this is an Imperial Liberation CB war
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 0.8 -- AI desire for a province is multiplied by this if it doesn't have a valid cb for it (only used when annexing, not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 25.0 -- AI desire for a province is multiplied by this if it has a core on it
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 150 -- AI desire for a province is multiplied by this if it is the wargoal
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 10.0 -- AI desire for a province is multiplied by this if it has a claim on it
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 1 -- AI desire for a province is multiplied by this if it is not the same culture
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 2 -- AI desire for a province is multiplied by this if it would go to their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_PROVINCE_REAL_ADJACENT_MULT = 5 -- AI desire for a province is increased by this multiplier for each owned adjacent province
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.4 -- AI desire for a province is multiplied by this if it is not adjacent at all (including vassals and other provinces being taken in peace)
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0.1 -- AI desire for a province is multiplied by this if it is not on their conquest list
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MIN_MULT = 0.75 -- AI desire for a province is multiplied by this if it has 99% overextension (not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 2.75 -- AI desire for a province is multiplied by this if it has 0% overextension (not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_ISOLATED_CAPITAL_MULT = 0.75 -- AI desire for a province if it is capital (costs a bit more to take)
NDefines.NAI.PEACE_TERMS_PROVINCE_ALLY_MULT = 0.65 -- AI desire for giving (non-core) provinces to its allies
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPORTANT_ALLY_MULT = 2 -- AI desire for giving provinces to allies that it has promised land
NDefines.NAI.PEACE_TERMS_TRADE_POWER_VALUE_MULT = 0.65 -- AI desire for transfering trade power is multiplied by this for each 01 trade value in shared nodes
NDefines.NAI.PEACE_TERMS_TRADE_POWER_VALUE_MAX = 2.75 -- Max AI desire for transfering trade power from shared node value
NDefines.NAI.PEACE_TERMS_TRADE_POWER_NO_TRADE_INTEREST_MULT = 0.5 -- AI desire for transfering trade power is multiplied by this if they are not a merchant republic
NDefines.NAI.PEACE_TERMS_HUMILIATE_VALUE_MULT = 1 -- AI desire for humiliating is multiplied by this for each 1 prestige the enemy has
NDefines.NAI.PEACE_TERMS_HUMILIATE_VALUE_MAX = 1.75 -- Max AI desire for humiliating its' enemy
NDefines.NAI.PEACE_TERMS_REVOKE_CORE_VASSAL_MULT = 0.6 -- AI desire for revoking cores is multiplied by this if the cores are on their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_REVOKE_CORE_FEAR_MULT = 1.75 -- AI desire for revoking cores is multiplied by this if they are afraid of the other country
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 5.0 -- AI desire for returning core provinces is multiplied by this for their vassals
NDefines.NAI.PEACE_TERMS_RETURN_CORES_NOT_FRIEND_MULT = 0.1 -- AI desire for returning core provinces is multiplied by this if they are not friends of the country core is being returned to
NDefines.NAI.PEACE_TERMS_RETURN_CORES_IMPERIAL_LIBERATION_MULT = 2.5 --AI desire for returning core province is multiplied by this if it's a target of Imperial Liberation CB war
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_NO_INTEREST_MULT = 0.1 -- AI desire for annuling a treaty is multiplied by this if they have no strategic interests in doing so
NDefines.NAI.PEACE_TERMS_PROVINCE_HRE_UNJUSTIFIED_MULT = 0.1 -- AI desire for a province is multiplied by this for HRE provinces if they are a member of the empire and don't have a CB, claim or core to it
NDefines.NAI.PEACE_TERMS_MIN_MONTHS_OF_GOLD = 5 -- If they don't have at least this much warscore worth of gold, prefer concede defeat
NDefines.NAI.PEACE_TERMS_PROVINCE_STRATEGY_THRESHOLD = 0.125 -- If province has at least this strategic priority, AI values it higher in peace deals
NDefines.NAI.PEACE_TERMS_RETURN_PROVINCE_STRATEGY_MULT = 0.35 -- If we have strategic priority on a province, AI desire to release it to another nation is multiplied by this amount
NDefines.NAI.PEACE_TERMS_EMPEROR_RELEASE_PRINCE = 50.0 -- This is added, not multiplied
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SIZE_MULT = 0.125 -- AI desire mult for releasing vassal increased by this for each province they hold
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_MAX_MULT = 1.5 -- Max AI desire mult for releasing vassals
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_HRE_MULT = 2.25 -- AI desire for releasing a vassal is multiplied by this if both are HRE members
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_ELECTOR_MULT = 10.0 -- AI desire for releasing an elector is multiplied by this for Emperor
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_MULT = 0.65 -- AI desire for releasing a country is multiplied by this if they are the same culture group as releaser
NDefines.NAI.PEACE_TERMS_RELEASE_VASSAL_SAME_CULTURE_GROUP_MULT = 0.75 -- AI desire for releasing a country is multiplied by this if they are the same culture group (but not same culture) as releaser
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_SIZE_MULT = 0.1 -- AI desire mult for releasing vassal increased by this for each province they hold
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_MAX_MULT = 1.3	-- Max AI desire mult for releasing vassals
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_HRE_MULT = 2.0 -- AI desire for releasing a vassal is multiplied by this if both are HRE members
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_ELECTOR_MULT = 10.0 -- AI desire for releasing an elector is multiplied by this for Emperor
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_SAME_CULTURE_MULT = 0.65 -- AI desire for releasing a country is multiplied by this if they are the same culture group as releaser
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSAL_SAME_CULTURE_GROUP_MULT = 0.75 -- AI desire for releasing a country is multiplied by this if they are the same culture group (but not same culture) as releaser
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SIZE_MULT = 0.01 -- AI desire mult for releasing countries is increased by this for each development they hold
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_MAX_MULT = 1.3 -- Max AI desire mult for releasing countries
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_KARMA_LOW_MULT = 1.5 --AI desire mult when below karma bonus
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_KARMA_VERY_LOW_MULT = 2.0 --AI desire mult when karma low enough for penalty
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_HRE_MULT = 2.0 -- AI desire for releasing a country is multiplied by this if both are HRE members
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_MULT = 0.65 -- AI desire for releasing a country is multiplied by this if they are the same culture group as releaser
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_SAME_CULTURE_GROUP_MULT = 0.75 -- AI desire for releasing a country is multiplied by this if they are the same culture group (but not same culture) as releaser
NDefines.NAI.PEACE_TERMS_MIL_ACCESS_BASE_MULT = 0 -- AI desire for mil access through peace
NDefines.NAI.PEACE_TERMS_FLEET_BASING_BASE_MULT = 0 -- AI desire for fleet basing rights through peace
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 0.2 -- AI desire for war reparations through peace
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_MIN_INCOME_RATIO = 0.9 -- AI only wants war reparations if other country has at least this % of their income

NDefines.NAI.DIPLOMATIC_ACTION_RANDOM_FACTOR = 1.0 -- How much of the AI diplomatic action scoring is randomly determined (10 = half random, 20 = 2/3rd random, etc)
NDefines.NAI.DIPLOMATIC_ACTION_PROPOSE_SCORE = 50 -- AI must score a diplomatic action at least this highly to propose it themselves
NDefines.NAI.DIPLOMATIC_ACTION_LIBERTY_DESIRE_CHANGE_SUBJECT_TYPE_MODIFIER = 0.1 -- how much of an impact liberty desire causes to the AI wanting to change subject type
NDefines.NAI.DIPLOMATIC_ACTION_BREAK_SCORE = 30 -- AI must score a diplomatic action less than this to break it off
NDefines.NAI.DIPLOMATIC_ACTION_PERSONALITY_MULT = 1.5 -- How much more the AI values a diplomatic action if it suits their personality (improve relations for diplomat, etc)

--CONVERT_TRIBUTARY_TO_VASSAL_AI_DESIRE_BASE = 20,
--CONVERT_TRIBUTARY_TO_VASSAL_AI_DESIRE_PREPARING_FOR_WAR_SCORE = 30,
--CONVERT_TRIBUTARY_TO_VASSAL_AI_DESIRE_WANTS_LAND_SCORE = 30,

NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_GOLD_BASE_SCORE = 50
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_GOLD_PREPARING_FOR_WAR_SCORE = 100
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_GOLD_WANTS_GOLD = 100
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_GOLD_CAPITALIST_MULT = 1.5

NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_MEN_BASE_SCORE = 50
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_MEN_PREPARING_FOR_WAR_SCORE = 100
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_MEN_MILITARIST_MULT = 1.5

NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_SAILORS_BASE_SCORE = 50
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_SAILORS_PREPARING_FOR_WAR_SCORE = 100
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_SAILORS_MILITARIST_MULT = 1.5

NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_HEIR_BASE_SCORE = 50
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_HEIR_SAME_DYNASTY_MULT = 0.5
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_HEIR_ALREADY_OVERLORD_MULT = 0.5

NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_TRUST_BASE_SCORE = 50
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_TRUST_PREPARING_FOR_WAR_SCORE = 50
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_TRUST_DIPLOMAT_MULT = 1.5

NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_WAR_PREP_BASE_SCORE = 20
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_WAR_PREP_PREPARING_FOR_WAR_SCORE = 150
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_FAVORS_FOR_WAR_PREP_MILITARIST_MULT = 1.5

NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_BASE_MULT = 33 -- AI scoring for offer condottieri, base scale
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_MONTHLY_PARTICIPATION_RATE = -0.1 --Base monthly decay in participation Related to multipliers for war participation (but doesn't depend on number of regiments, so raw multiplier matters)
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_PARTICIPATION_BREAK = -1.8 --At this level of (lack of) participation from the player, the AI will break the condottieri agreement and tell all their friends
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_PARTICIPATION_WARN = -1.2 --At this level of (lack of) participation from the player, a warning alert will be displayed about impendent AI discontent
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_HIRING_MALUS_YEARS = 15 --Once AI has told all their friends about how mean a player is, they will refuse to hire condottieri for cash this long
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_PARTICIPATION_FROM_CASUALTIES = 0.5 --Scaler for casulties caused by condottieri
NDefines.NAI.DIPLOMATIC_ACTION_ALLIANCE_ACCEPTANCE_MULT = 2.25 -- AI scoring for alliance based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_KNOWLEDGE_SHARING_ACCEPTANCE_MULT = 30 -- AI scoring for knowledge sharing based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_SHAREMAP_REGION_SELF_VALUE_MULT = 15 -- AI scoring for sharing maps based on "interests in region" for map sharing
NDefines.NAI.DIPLOMATIC_ACTION_SHAREMAP_PRESTIGE_FACTOR = 0.5 --AI scoring for sharing maps factor for current prestige
NDefines.NAI.DIPLOMATIC_ACTION_FEDERATION_ACCEPTANCE_MULT = 3.0 -- AI scoring for alliance based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_FEDERATION_ACCEPTANCE_INERTIA = 10 --new score must be at least this much better that current federation's score to move
NDefines.NAI.DIPLOMATIC_ACTION_ROYAL_MARRIAGE_ACCEPTANCE_MULT = 20 -- AI scoring for royal marriage based on their willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_ROYAL_MARRIAGE_NO_POWER_COST_RELATION_MULT = 0.25 -- AI scoring for royal marriage is multiplied by this if they currently lack a relation with a power cost
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_BEFRIEND_FACTOR = 190 -- AI scoring for improve relations is increased by this if they have an attitude with 'befriend' desire
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_ALLY_FACTOR = 190 -- AI scoring for improve relations is increased by this if they have an attitude with 'ally' desire
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_JOIN_HRE_FACTOR = 500 -- AI scoring for improve relations with the emperor is increased by this if they want to join the HRE
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_VASSALIZE_FACTOR = 200 -- AI scoring for improve relations is increased by this if they have an attitude with 'vassalize' desire (also applied to royal marriage desire)
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_SUPPORTING_HEIR_FACTOR = 50 -- AI scoring for improve relations is increased by this if they are also supporting a heir in the country
NDefines.NAI.DIPLOMATIC_ACTION_GRANT_ELECTORATE_PROVINCE_PENALTY_THRESHOLD = 4 -- AI scoring for grant electorate is reduced if target has at least this many provinces
NDefines.NAI.DIPLOMATIC_ACTION_GRANT_ELECTORATE_PROVINCE_PENALTY_MULT = 0.5 -- AI scoring for grant electorate is multiplied by this for each province above threshold
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_TRADE_INTEREST_FACTOR = 25 -- AI scoring for embargo is increased by this if they have trade interest
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_WAR_FACTOR = 50 -- AI scoring for embargo is increased by this if they are at war
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_TRADE_POWER_THRESHOLD = 1 -- AI will not embargo unless value of shared nodes is at least this high
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_TRADE_POWER_FACTOR = 25.0 -- AI scoring for embargo is increased by this for each 10 value in shared nodes
NDefines.NAI.DIPLOMATIC_ACTION_EMBARGO_COALITION_TARGET_MULT = 20 -- AI scoring for embargo is multiplied by this against coalition target
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_PEACE_MULT = 0.5 -- AI scoring for military access is multiplied by this if at peace
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_EXISTING_RELATION_MULT = 20.0 -- AI scoring for military access is multiplied by this if it has an existing power cost relation
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_ENEMY_REGIMENTS_FACTOR = 2.5 -- AI scoring for military access is increased by this for each enemy regiment they are sheltering
NDefines.NAI.DIPLOMATIC_ACTION_VASSALIZE_DEVELOPMENT_FACTOR = 100 -- AI scoring for vassalize is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_ANNEX_DEVELOPMENT_FACTOR = 50 -- AI scoring for demand annexation is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_INTEGRATE_DEVELOPMENT_FACTOR = 50 -- AI scoring for integrate is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_ANTAGONIZE_FACTOR = 20 -- AI scoring for excommunicate is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_ANNEX_FACTOR = 20 -- AI scoring for excommunicate is increased by this if they have an attitude with 'annex' desire
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_NEIGHBOUR_FACTOR = 25 -- AI scoring for excommunicate is increased by this if they are neighbours
NDefines.NAI.DIPLOMATIC_ACTION_EXCOMMUNICATE_RIVAL_FACTOR = 35 -- AI scoring for excommunicate is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_DEVELOPMENT_FACTOR = 10 -- AI scoring for crusade is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_ANTAGONIZE_FACTOR = 25 -- AI scoring for crusade is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_ANNEX_FACTOR = 50 -- AI scoring for crusade is increased by this if they have an attitude with 'annex' desire
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_NEIGHBOUR_FACTOR = 25 -- AI scoring for crusade is increased by this if they are neighbours
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_RIVAL_FACTOR = 10 -- AI scoring for crusade is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MAX_DEVELOPMENT_DIFFERENCE = 20 -- AI will not claim throne if target has more than their development * this value
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MIN_PRESTIGE_DIFFERENCE = 20 -- AI will not claim throne if they don't have at least this much more prestige
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MAX_DISTANCE = 100 -- AI will not claim throne if border distance is higher than this
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_VASSALIZE_FACTOR = 100 -- AI scoring for claim throne is increased by this if they have an attitude with 'vassalize' desire
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_DEVELOPMENT_FACTOR = 1 -- AI scoring for claim throne is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_DEVELOPMENT_MAX = 100 -- Max amount of AI scoring for claim throne from province development
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_OUR_CLAIMS_FACTOR = -50 -- AI scoring for claim throne is changed by this for each other throne they are claiming
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_OTHER_CLAIMS_FACTOR = -25 -- AI scoring for claim throne is changed by this for each other country claiming the target's throne
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_PROTECT_FACTOR = 50 -- AI scoring for guarantee is changed by this if they have an attitude with the 'protect' desire
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_MAX_DISTANCE = 50 -- AI will not warn if border distance is higher than this
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_WARN_FACTOR = 50 -- AI scoring for warning is changed by this if they have an attitude with the 'warn' desire (multiplied by number of common neighbors )
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_RELATIONS_THRESHOLD = 90 -- AI will only insult if relations are above this amount
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_ANTAGONIZE_FACTOR = 50 -- AI scoring for insults is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_ANNEX_FACTOR = 50	-- AI scoring for insults is increased by this if they have an attitude with 'annex' desire
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_RIVAL_FACTOR = 10 -- AI scoring for insults is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_INSULT_PREPARING_WAR_FACTOR = 200 -- AI scoring for insults is increased by this if it is preparing for war with them
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 1000 -- AI scoring for fabricating claims is always increased by this as long as the province is a conquest priority
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 20 -- AI scoring for fabricating claims based on strategic conquest priorities
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 15 -- AI scoring for fabricating claims if they already have another CB usable on the province
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_NOT_ADJACENT_FACTOR = 0.5 -- AI scoring for fabricating claims if the province is not adjacent
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_EMPEROR_FACTOR = 0.5 -- AI scoring for fabricating claims if province is HRE and they are emperor (does not stack with the above penalty)
NDefines.NAI.DIPLOMATIC_ACTION_SOW_DISCONTENT_ANTAGONIZE_FACTOR = 25 -- AI scoring for sowing discontent is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SOW_DISCONTENT_RIVAL_FACTOR = 25 -- AI scoring for sowing discontent is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_ANTAGONIZE_FACTOR = 25 -- AI scoring for agitating for liberty is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_RIVAL_FACTOR = 25 -- AI scoring for agitating for liberty is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_DEVELOPMENT_FACTOR = 0.25 -- AI scoring for agitate for liberty multiplied by development of subject agitated
NDefines.NAI.DIPLOMATIC_ACTION_AGITATE_FOR_LIBERTY_LD_FACTOR = 2 -- AI scoring for agitate for liberty multiplied by liberty desire percentage of subject agitated
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_REPUTATION_ANTAGONIZE_FACTOR = 25 -- AI scoring for sabotage reputation is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_REPUTATION_RIVAL_FACTOR = 25 -- AI scoring for sabotage reputation is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_STEAL_MAPS_ANTAGONIZE_FACTOR = 25 -- AI scoring for map stealing is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_STEAL_MAPS_REGION_RIVAL_VALUE_MULT = 0.25 -- AI scoring multiplier for map stealing is increased by this for region's value to rivals
NDefines.NAI.DIPLOMATIC_ACTION_STEAL_MAPS_REGION_SELF_VALUE_MULT = 0.5 -- AI scoring multiplier for map stealing is increased by this for region's value to self
NDefines.NAI.DIPLOMATIC_ACTION_SLANDER_MERCHANTS_ANTAGONIZE_FACTOR = 25 -- AI scoring for slander merchants is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SLANDER_MERCHANTS_RIVAL_FACTOR = 25 -- AI scoring for slander merchants is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_RECRUITMENT_ANTAGONIZE_FACTOR = 50 -- AI scoring for sabotage recruitment is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_SABOTAGE_RECRUITMENT_RIVAL_FACTOR = 50 -- AI scoring for sabotage recruitment is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_CORRUPT_OFFICIALS_ANTAGONIZE_FACTOR = 25 -- AI scoring for slander merchants is increased by this if they have an attitude with 'antagonize' desire
NDefines.NAI.DIPLOMATIC_ACTION_CORRUPT_OFFICIALS_RIVAL_FACTOR = 25 -- AI scoring for corrupt officials is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_DISTANCE_FACTOR = 100 -- AI scoring for joining/forming coalition based on distance
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_THREAT_FACTOR = 0.5 -- AI scoring for joining/forming coalition based on threat score
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_RELATIONS_FACTOR = 0.5 -- AI scoring for joining/forming coalition based on negative relations
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_SIZE_FACTOR = 1 -- AI scoring for joining/forming coalition based on number of cities
NDefines.NAI.DIPLOMATIC_ACTION_COALITION_SIZE_FACTOR_MAX = 50 -- Size factor will not go above this regardless of number of cities
NDefines.NAI.DIPLOMATIC_ACTION_ENFORCE_PEACE_FORCE_BALANCE_MULT = 1 -- AI scoring for enforce peace is multiplied by this
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_WAR_WITH_RIVAL_FACTOR = 30 -- AI scoring for giving subsidies to a country that is at war with its rival
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_RELATIVE_INCOME_FACTOR = 30 -- AI scoring for giving subsidies to a country based on its relative income to the AI nation (lower income = higher scoring)
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_RELATIONS_FACTOR = 0.3 -- AI scoring for giving subsidies to a country based on opinion of the other country
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_RELATIONS_MAX = 100 -- Relations above this will not be considered for DIPLOMATIC_ACTION_SUBSIDIES_RELATIONS_FACTOR
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_MAX_OCCUPIED = 0.5 -- Max fraction of a country that can be occupied/besieged for AI to consider it worth giving subsidies
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_MAX_RELATIVE_INCOME = 0.33 -- Max relative montly income that a country can have for the AI to consider it in need of subsidies
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_PREVIOUS_SUBSIDIES_FACTOR = -100 -- AI scoring for giving subsidies based on previous subsidies nation is receiving relative to income
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_INDEBTED_FACTOR = 20 -- AI scoring for giving subsidies to an ally in heavy debt
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_MIN_VALUE = 0.5 -- Minimum amount of subsidies that AI considers worthwhile
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_ACCEPTANCE_MULT = 30 -- AI scoring for transfer trade power based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_STEER_TRADE_ACCEPTANCE_MULT = 30 -- AI scoring to retain trade steering based on willingness to accept it if offered to them
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_TRADE_INTEREST_FACTOR = 25 -- AI scoring for transfer trade power is increased by this if they have trade interest
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_THRESHOLD = 10 -- AI will not ask to transfer trade power unless value of shared nodes is at least this high
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_FACTOR = 25.0 -- AI scoring for transfer trade power is increased by this for each 10 value in shared nodes
NDefines.NAI.DIPLOMATIC_ACTION_TRADE_POWER_ALLIANCE_FACTOR = 0.25 -- AI threshold for transfer trade power will be mulitplied by this if the two countries have an alliance
NDefines.NAI.DIPLOMATIC_ACTION_SUPPORT_HEIR_DEVELOPMENT_FACTOR = 2 -- AI scoring for support heir is increased by this for each development in target's provinces
NDefines.NAI.DIPLOMATIC_ACTION_SUPPORT_HEIR_ALLIANCE_FACTOR = 2 -- AI scoring for support heir is multiplied by this if the two countries have an alliance
NDefines.NAI.DIPLOMATIC_ACTION_BUILD_SPY_NETWORK_RIVAL_FACTOR = 50 -- AI scoring to build spy network in neighboring rivals, or overlord if disloyal subject
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 12.5				-- Multiplier for how much the AI values having much development in accepted cultures
NDefines.NAI.AI_PROPORTION_OF_DEV_CULTURE_MULTIPLIER = 30		-- Multiplier for how much the AI wants to convert brother cultures in terms of percentage of the nation Essentially we compare the total dev of the non-promoted culture * AI_TOTAL_DEV_CULTURE_MULTIPLIER with the proportion of dev of the country * AI_PROPORTION_OF_DEV_CULTURE_MULTIPLIER and choose the larger of the two as our desire to add an accepted culture
NDefines.NAI.AI_BROTHER_CULTURE_MULTIPLIER = 0.75					-- How much multiplier for how much the AI wants to convert brother cultures (there's less penalty on them not being the same culture because they're at least close)
NDefines.NAI.DIPLOMATIC_ACTION_INFILTRATE_BASE_FACTOR = 25 -- AI infiltrate administration base scoring
NDefines.NAI.DIPLOMATIC_ACTION_INFILTRATE_POWER_FACTOR = 5 -- AI base scoring for infiltrate administration is multiplied by at most this proportion of relative military strength
NDefines.NAI.DIPLOMATIC_ACTION_INFILTRATE_RIVAL_FACTOR = 25 -- AI scoring for infiltrate administration is increased by this if they are rivals
NDefines.NAI.DIPLOMATIC_ACTION_COUNTER_ESPIONAGE_SPY_PROPENSITY_FACTOR = 0.4 -- AI scoring for counter espionage depending on how many spy network points they spent in recent years
NDefines.NAI.DIPLOMATIC_ACTION_COUNTER_ESPIONAGE_ENEMY_FACTOR = 25 --AI scoring for counter espionage against an active enemy (someone we're at war with, antagonize or otherwise rival)
NDefines.NAI.DIPLOMATIC_ACTION_TRIBUTARY_ACCEPTANCE_PER_DEVELOPMENT = -0.5	-- AI scoring for accepting becoming a tributary state per raw development
NDefines.NAI.DIPLOMATIC_ACTION_TRIBUTARY_EMPIRE_FACTOR = 10			-- AI scoring for establishing Tributary States is increased by this if actor is Celestial Emperor or has horde government with rank Empire
NDefines.NAI.ALLIANCE_DESIRE_TOO_MANY_RELATIONS = -20				-- AI desire/acceptance for alliance when it has or will get too many relations Multiplies with number of relations above limit
NDefines.NAI.SUPPORT_INDEPENDENCE_DESIRE_TOO_MANY_RELATIONS = -20 -- AI desire/acceptance for supporting independence when it has or will get too many relations Multiplies with number of relations above limit
NDefines.NAI.MARRIAGE_DESIRE_TOO_MANY_RELATIONS = -50				-- AI desire/acceptance for royal marriange when it has or will get too many relations Multiplies with number of relations above limit
NDefines.NAI.GUARANTEE_DESIRE_TOO_MANY_RELATIONS = -50			-- AI desire for guaranteeing when it has or will get too many relations Multiplies with number of relations above limit

-- AI parameters for not considering diplomacy with all other countries every day (for performance)
--FOREIGN_MINISTER_IGNORE_DISTANCE_BASE = 8,
--FOREIGN_MINISTER_BASE_PROVINCE_COUNT = 2,

NDefines.NAI.DIPLOMATIC_ACTION_CURRY_FAVORS_DEVELOPMENT_FACTOR = 0.2 
NDefines.NAI.DIPLOMATIC_ACTION_CURRY_FAVORS_ALLIANCE_FACTOR = 4

NDefines.NAI.INVADING_BRAVERY = 1.275									-- If (defender strength) / (invader strength) > INVADING_BRAVERY, the AI won't attempt a naval invasion
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1.9							-- AI will never send more than this ratio to invade (Measured in strength)
NDefines.NAI.HOME_FLEET_MAX_RATIO = 0.85							-- Maximum proportion of warships in home fleet
NDefines.NAI.TRADE_POLICY_PROPAGATE_RELIGION_SCORE = 50.0				-- Score for propagate religion trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_PREPARING_FOR_WAR_PER_PROVINCE_SCORE = 6.0	-- Score per enemy province while preparing war for attack bonus trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_AT_WAR_PER_PROVINCE_SCORE = 5.5				-- Score per enemy province while preparing war for attack bonus trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_MAXIMIZE_PROFITS_SCORE = 9.0					-- Score for maximize profit trade policy
NDefines.NAI.TRADE_POLICY_IMPROVE_RELATIONS_PER_COUNTRY_SCORE = 5.0		-- Score per country with merchant for improve relations policy
NDefines.NAI.TRADE_POLICY_SPY_OFFENCE_PER_COUNTRY_SCORE = 5.0			-- Score per country with merchant for spy offence policy
NDefines.NAI.DRILL_BONUS_WAR_READINESS = 0.08							-- Bonus for war readiness of drilled units
NDefines.NAI.MONTHS_STOP_DRILLING_BEFORE_WAR = 5						-- Months before a prepared war to stop drilling
NDefines.NAI.DRILLING_BUDGET_OF_SURPLUS = 0.01							-- Max amount of surplus to be used for drilling
NDefines.NAI.DRILLING_DEBT_SURPLUS_RATIO_THRESHOLD = 0.025			-- AI will only consider drilling if Surplus / Debt ratio is above
NDefines.NAI.DRILLING_ACCEPTABLE_THREAT_REDUCTION = 100					-- Acceptable threat reduction for drilling
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 50					-- AI will assign estates up to ESTATE_DANGER_THRESHOLD minus this (See ai_territory_modifier)
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 1						-- AI will be reuluctant to fire advisors with skill above this (due to prior investment)
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 40							-- AI will not promote advisors above this age
--FIRE_ADVISOR_LOAN_REQUIREMENT = 5,							-- AI will not fire advisors until it has this many loans
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.125				-- AI will only assign armies larger that this to a region
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 40				-- Max amount of armies to use in new region assignment algorithm (fall back to old one)
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 80				-- Max amount of tasks to use in new region assignment algorithm (fall back to old one)
NDefines.NAI.ELECTORAL_REFORMATION_CONVERT_TRESHOLD = 01				-- How much of an electors development needs to be a reformed religion for it to try and reform
NDefines.NAI.TRADE_COMPANY_INVESTMENT_COST_THRESHOLD = 10				-- How many times the cost of the investment must be in the treasury to consider buying it
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 1000					-- Influence on assimilation interest from number of provinces left to conquer
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 12				-- If AI fails to find an army for an invasion it will try again in this number of days
NDefines.NAI.CHARTER_COMPANY_BASE_RELUCTANCE = -3						-- Base reluctance to giving away provinces in charter company diplo action
NDefines.NAI.CHARTER_COMPANY_DEVELOPMENT_RELUCTANCE = 3		

NDefines.NAI.WAR_WARSCORE_TO_JOIN = -100								-- Minimum warscore for the AI to join a call for arms
NDefines.NAI.WAR_MIN_WARSCORE_TO_JOIN = -5								-- Starting warscore for the AI to join a call for arms
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT = 0.45						-- Army <-> province distance impact on province evaluation
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 9.0							-- Border <-> province distance impact on province evaluation
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.025							-- AI will try to defend provinces under threat worth more than this percentage of total development
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 20				-- Homeland priorization when assigning armies to regions (only applied when actually threatened)
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.2							-- The most an AI will spend of its income on a missionary
NDefines.NAI.BUY_INDULGENCE_BASE_AI_DESIRE = -1						-- AI desire for buy indulgence if curia controller has negative opinion of it, multiplied by budget/cost
NDefines.NAI.BUY_INDULGENCE_OPINION_AI_DESIRE_MULTIPLIER = -0.01
NDefines.NAI.BUY_INDULGENCE_RIVAL_AI_DESIRE = -1						-- AI desire for buy indulgence if curia controller rivaled it, multiplied by budget/cost
NDefines.NAI.BUY_INDULGENCE_EXCOM_AI_DESIRE = -1					-- AI desire for buy indulgence if it's excommunicated, multiplied by budget/cost
NDefines.NAI.APPOINT_CARDINAL_CORRUPTION_THRESHOLD = 0					-- Upper bound to the corruption the Papal State should have before appoint cardinals in its own land
NDefines.NAI.APPOINT_CARDINAL_IN_OWNED_LAND_AI_DESIRE = 0.01				-- AI scoring for appoint cardinals in owned land, multiplied by budget/cost
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_BASE_AI_DESIRE = 50.0				-- AI scoring for upgrade centers of trade, multiplied by budget/cost
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_AI_POWER_DESIRE = 5.0				-- AI scoring for upgrade centers of trade, division on the amount of trade power AI has in node
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 10000						-- AI scoring for redruiting advisors, multiplied by budget/cost
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 50.0						-- AI scoring for promoting advisors, multiplied by budget/cost
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = -1						-- AI scoring for becoming defender of faith, multiplied by budget/cost
NDefines.NAI.CALL_ECUMENICAL_COUNCIL_BASE_AI_DESIRE = -1				-- AI scoring for calling ecumenical council, multiplied by budget/cost
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 1						-- AI scoring for repaying loans, multiplied by (MAX(budget - other loans, 0) * number_of_loans)/cost
-- Used for the diplomatic action
NDefines.NAI.APPOINT_CARDINAL_SHARE_OF_TREASURY = 0.1					-- Share of treasury upper bound to the cost of appoint cardinal for the Papal State to appoint cardinals in its own land
NDefines.NAI.APPOINT_CARDINAL_WANTS_BEFRIEND = 200						-- AI scoring for appoint cardinals is increased by this if they have an attitude with 'befriend' desire
NDefines.NAI.APPOINT_CARDINAL_WANTS_ALLY = 200				-- AI scoring for appoint cardinals is increased by this if they have an attitude with 'ally' desire
NDefines.NAI.APPOINT_CARDINAL_CAN_INTEGRATE = 150				-- AI scoring for appoint cardinals is increased by this if they can integrate/annex the target and inherit the cardinals
NDefines.NAI.ESTATE_PRIVILEGE_REVOKE_THRESHOLD = 51
NDefines.NAI.ESTATE_PRIVILEGE_GRANT_THRESHOLD = 0
--ESTATE_PRIVILEGE_LAST_PENALTY = 3,							-- The GRANT and REVOKE thresholds are moved up by this much for the final slot
NDefines.NAI.ESTATE_INTERACTION_THRESHOLD = 49.9
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 73.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 0
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4
NDefines.NAI.MIN_SCORE_TO_CONCENTRATE_DEVELOPMENT = 15


NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.1							-- Amount in percent to increase/decrease spending on budget posts when adjusting due to surplus/deficit
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 0.8					-- Above what rebel threat should the AI militarize (i.e. focus spending on armies)
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 1.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 0.0
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 1.5
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 1.5
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 0.9
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.25
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 1.25
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 1.25
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 1.33
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 1.25
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 0.8
NDefines.NAIEconomy.MISSIONARY_FRACTION = 0.15
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.1
NDefines.NAIEconomy.BASE_SAVINGS_PRIORITY = 0.5
NDefines.NAIEconomy.BASE_SAVINGS_PRIORITY_WARTIME = 0.0
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1.0			-- Per loan
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 0.5		-- Per loan
NDefines.NAIEconomy.SUBSIDY_PRIORITY_CONSIDERATION_THRESHOLD = 50.0
NDefines.NAIEconomy.SUBSIDY_DESIRE_TO_PRIORITY_RATIO = 0.05
NDefines.NAIEconomy.SUBSIDY_MAX_BUDGET_FRACTION = 0.05


NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.STARTING_HARMONY = 50.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 2.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -5.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0

NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.1
NDefines.NGovernment.COSSACKS_ABILITY_COSSACKS_SPAWN_SIZE = 0.1
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
NDefines.NGovernment.EXPAND_INFRASTRUCTURE_ADM_COST = 25
